src/SaaS.SDK.PublisherSolution/Controllers/OffersController.cs
namespace Microsoft.Marketplace.Saas.Web.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text.Json;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.Rendering;
    using Microsoft.Extensions.Logging;
    using Microsoft.Marketplace.SaaS.SDK.Services.Models;
    using Microsoft.Marketplace.SaaS.SDK.Services.Services;
    using Microsoft.Marketplace.SaaS.SDK.Services.Utilities;
    using Microsoft.Marketplace.SaasKit.Client.DataAccess.Contracts;
    using Microsoft.Marketplace.SaasKit.Client.DataAccess.Entities;

    /// <summary>
    /// Offers Controller.
    /// </summary>
    /// <seealso cref="Microsoft.Marketplace.Saas.Web.Controllers.BaseController" />
    [ServiceFilter(typeof(KnownUserAttribute))]
    public class OffersController : BaseController
    {
        private readonly IUsersRepository usersRepository;

        private readonly IValueTypesRepository valueTypesRepository;

        private readonly IApplicationConfigRepository applicationConfigRepository;

        private readonly IOffersRepository offersRepository;

        private readonly IOfferAttributesRepository offersAttributeRepository;

        private readonly ILogger<OffersController> logger;

        private OfferServices offersService;

        /// <summary>
        /// Initializes a new instance of the <see cref="OffersController"/> class.
        /// </summary>
        /// <param name="offersRepository">The offers repository.</param>
        /// <param name="applicationConfigRepository">The application configuration repository.</param>
        /// <param name="usersRepository">The users repository.</param>
        /// <param name="valueTypesRepository">The value types repository.</param>
        /// <param name="offersAttributeRepository">The offers attribute repository.</param>
        /// <param name="logger">The logger.</param>
        public OffersController(IOffersRepository offersRepository, IApplicationConfigRepository applicationConfigRepository, IUsersRepository usersRepository, IValueTypesRepository valueTypesRepository, IOfferAttributesRepository offersAttributeRepository, ILogger<OffersController> logger)
        {
            this.offersRepository = offersRepository;
            this.applicationConfigRepository = applicationConfigRepository;
            this.usersRepository = usersRepository;
            this.valueTypesRepository = valueTypesRepository;
            this.offersService = new OfferServices(this.offersRepository);
            this.offersAttributeRepository = offersAttributeRepository;
            this.logger = logger;
        }

        /// <summary>
        /// Indexes this instance.
        /// </summary>
        /// <returns>return All subscription.</returns>
        public IActionResult Index()
        {
            this.logger.LogInformation("Offers Controller / Index");
            try
            {
                List<OffersModel> getAllOffersData = new List<OffersModel>();
                this.TempData["ShowWelcomeScreen"] = "True";
                var currentUserDetail = this.usersRepository.GetPartnerDetailFromEmail(this.CurrentUserEmailAddress);

                getAllOffersData = this.offersService.GetOffers();

                return this.View(getAllOffersData);
            }
            catch (Exception ex)
            {
                this.logger.LogError(ex, ex.Message);
                return this.View("Error", ex);
            }
        }

        /// <summary>
        /// Indexes this instance.
        /// </summary>
        /// <param name="offerGuId">The offer gu identifier.</param>
        /// <returns>
        /// return All subscription.
        /// </returns>
        public IActionResult OfferDetails(Guid offerGuId)
        {
            this.logger.LogInformation("Offers Controller / OfferDetails:  offerGuId {0}", offerGuId);
            try
            {
                OffersViewModel offersData = new OffersViewModel();
                this.TempData["ShowWelcomeScreen"] = "True";
                var currentUserDetail = this.usersRepository.GetPartnerDetailFromEmail(this.CurrentUserEmailAddress);
                offersData = this.offersService.GetOfferOnId(offerGuId);

                var offerAttributes = this.offersAttributeRepository.GetInputAttributesByOfferId(offerGuId);
                var valueTypes = this.valueTypesRepository.GetAll().ToList();
                this.ViewBag.ValueTypes = new SelectList(valueTypes, "ValueTypeId", "ValueType");
                offersData.OfferAttributes = new List<OfferAttributesModel>();
                if (offerAttributes != null)
                {
                    foreach (var offerAttribute in offerAttributes)
                    {
                        var existingOfferAttribute = new OfferAttributesModel()
                        {
                            AttributeID = offerAttribute.Id,
                            ParameterId = offerAttribute.ParameterId,
                            DisplayName = offerAttribute.DisplayName,
                            Description = offerAttribute.Description,
                            ValueTypeId = offerAttribute.ValueTypeId,
                            FromList = offerAttribute.FromList,
                            ValuesList = offerAttribute.ValuesList,
                            Max = offerAttribute.Max,
                            Min = offerAttribute.Min,
                            Type = offerAttribute.Type,
                            DisplaySequence = offerAttribute.DisplaySequence,
                            Isactive = offerAttribute.Isactive,
                            IsRequired = offerAttribute.IsRequired ?? false,
                            IsDelete = offerAttribute.IsDelete ?? false,
                            CreateDate = DateTime.Now,
                            UserId = currentUserDetail == null ? 0 : currentUserDetail.UserId,
                            OfferId = offersData.OfferGuid,
                        };
                        offersData.OfferAttributes.Add(existingOfferAttribute);
                    }
                }

                return this.PartialView(offersData);
            }
            catch (Exception ex)
            {
                this.logger.LogError("Message:{0} :: {1}   ", ex.Message, ex.InnerException);
                return this.View("Error", ex);
            }
        }

        /// <summary>
        /// Indexes this instance.
        /// </summary>
        /// <param name="offersData">The offers data.</param>
        /// <returns>
        /// return All subscription.
        /// </returns>
        [HttpPost]
        public IActionResult OfferDetails(OffersViewModel offersData)
        {
            this.logger.LogInformation("Offers Controller / OfferDetails:  offerGuId {0}", JsonSerializer.Serialize(offersData));
            try
            {
                var currentUserDetail = this.usersRepository.GetPartnerDetailFromEmail(this.CurrentUserEmailAddress);
                if (offersData != null && offersData.OfferAttributes != null)
                {
                    // query
                    var validItems = offersData.OfferAttributes.Where(i => i.IsRemove == false);

                    foreach (var offerAttribute in validItems)
                    {
                        var newOfferAttribute = new OfferAttributes()
                        {
                            Id = offerAttribute.AttributeID,
                            ParameterId = offerAttribute.ParameterId,
                            DisplayName = offerAttribute.DisplayName,
                            Description = offerAttribute.Description,
                            ValueTypeId = offerAttribute.ValueTypeId,
                            FromList = offerAttribute.FromList,
                            ValuesList = offerAttribute.ValuesList,
                            Max = offerAttribute.Max,
                            Min = offerAttribute.Min,
                            Type = offerAttribute.Type,
                            DisplaySequence = offerAttribute.DisplaySequence,
                            Isactive = offerAttribute.Isactive,
                            IsRequired = offerAttribute.IsRequired,
                            IsDelete = offerAttribute.IsDelete,
                            CreateDate = DateTime.Now,
                            UserId = currentUserDetail == null ? 0 : currentUserDetail.UserId,
                            OfferId = offersData.OfferGuid,
                        };
                        this.offersAttributeRepository.Add(newOfferAttribute);
                    }

                    var valueTypes = this.valueTypesRepository.GetAll().ToList();
                    this.ViewBag.ValueTypes = new SelectList(valueTypes, "ValueTypeId", "ValueType");
                    this.TempData["ShowWelcomeScreen"] = "True";
                }

                this.ModelState.Clear();
                return this.RedirectToAction(nameof(this.OfferDetails), new { @offerGuId = offersData.OfferGuid });
            }
            catch (Exception ex)
            {
                this.logger.LogError(ex, ex.Message);
                return this.View("Error", ex);
            }
        }
    }
}

src/SaaS.SDK.PublisherSolution/Controllers/PlansController.cs
namespace Microsoft.Marketplace.Saas.Web.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text.Json;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.Extensions.Logging;
    using Microsoft.Marketplace.SaaS.SDK.Services.Models;
    using Microsoft.Marketplace.SaaS.SDK.Services.Services;
    using Microsoft.Marketplace.SaaS.SDK.Services.Utilities;
    using Microsoft.Marketplace.SaasKit.Client.DataAccess.Contracts;

    /// <summary>
    /// Plans Controller.
    /// </summary>
    /// <seealso cref="Microsoft.Marketplace.Saas.Web.Controllers.BaseController" />
    [ServiceFilter(typeof(KnownUserAttribute))]
    public class PlansController : BaseController
    {
        /// <summary>
        /// The subscription repository.
        /// </summary>
        private readonly ISubscriptionsRepository subscriptionRepository;

        /// <summary>
        /// The users repository.
        /// </summary>
        private readonly IUsersRepository usersRepository;

        private readonly IApplicationConfigRepository applicationConfigRepository;

        private readonly IPlansRepository plansRepository;

        private readonly IOffersRepository offerRepository;

        private readonly IOfferAttributesRepository offerAttributeRepository;

        private readonly ILogger<OffersController> logger;

        private PlanService plansService;

        /// <summary>
        /// Initializes a new instance of the <see cref="PlansController" /> class.
        /// </summary>
        /// <param name="subscriptionRepository">The subscription repository.</param>
        /// <param name="usersRepository">The users repository.</param>
        /// <param name="applicationConfigRepository">The application configuration repository.</param>
        /// <param name="plansRepository">The plans repository.</param>
        /// <param name="offerAttributeRepository">The offer attribute repository.</param>
        /// <param name="offerRepository">The offer repository.</param>
        /// <param name="logger">The logger.</param>
        public PlansController(ISubscriptionsRepository subscriptionRepository, IUsersRepository usersRepository, IApplicationConfigRepository applicationConfigRepository, IPlansRepository plansRepository, IOfferAttributesRepository offerAttributeRepository, IOffersRepository offerRepository, ILogger<OffersController> logger)
        {
            this.subscriptionRepository = subscriptionRepository;
            this.usersRepository = usersRepository;
            this.applicationConfigRepository = applicationConfigRepository;
            this.plansRepository = plansRepository;
            this.offerAttributeRepository = offerAttributeRepository;
            this.offerRepository = offerRepository;
            this.logger = logger;
            this.plansService = new PlanService(this.plansRepository, this.offerAttributeRepository, this.offerRepository);
        }

        /// <summary>
        /// Indexes this instance.
        /// </summary>
        /// <returns>return All subscription.</returns>
        public IActionResult Index()
        {
            this.logger.LogInformation("Plans Controller / OfferDetails:  offerGuId");
            try
            {
                List<PlansModel> getAllPlansData = new List<PlansModel>();
                this.TempData["ShowWelcomeScreen"] = "True";
                var currentUserDetail = this.usersRepository.GetPartnerDetailFromEmail(this.CurrentUserEmailAddress);

                getAllPlansData = this.plansService.GetPlans();

                return this.View(getAllPlansData);
            }
            catch (Exception ex)
            {
                this.logger.LogError(ex, ex.Message);
                return this.View("Error", ex);
            }
        }

        /// <summary>
        /// Indexes this instance.
        /// </summary>
        /// <param name="planGuId">The plan gu identifier.</param>
        /// <returns>
        /// return All subscription.
        /// </returns>
        public IActionResult PlanDetails(Guid planGuId)
        {
            this.logger.LogInformation("Plans Controller / PlanDetails:  planGuId {0}", planGuId);
            try
            {
                PlansModel plans = new PlansModel();
                this.TempData["ShowWelcomeScreen"] = "True";
                var currentUserDetail = this.usersRepository.GetPartnerDetailFromEmail(this.CurrentUserEmailAddress);
                plans = this.plansService.GetPlanDetailByPlanGuId(planGuId);
                return this.PartialView(plans);
            }
            catch (Exception ex)
            {
                this.logger.LogError(ex, ex.Message);
                return this.View("Error", ex);
            }
        }

        /// <summary>
        /// Indexes this instance.
        /// </summary>
        /// <param name="plans">The plans.</param>
        /// <returns>
        /// return All subscription.
        /// </returns>
        [HttpPost]
        public IActionResult PlanDetails(PlansModel plans)
        {
            this.logger.LogInformation("Plans Controller / PlanDetails:  plans {0}", JsonSerializer.Serialize(plans));
            try
            {
                var currentUserDetail = this.usersRepository.GetPartnerDetailFromEmail(this.CurrentUserEmailAddress);
                if (plans != null)
                {
                    if (plans.PlanAttributes != null)
                    {
                        var inputAtttributes = plans.PlanAttributes.Where(s => s.Type.ToLower() == "input").ToList();
                        foreach (var attributes in inputAtttributes)
                        {
                            attributes.UserId = currentUserDetail.UserId;
                            this.plansService.SavePlanAttributes(attributes);
                        }
                    }

                    if (plans.PlanEvents != null)
                    {
                        foreach (var events in plans.PlanEvents)
                        {
                            events.UserId = currentUserDetail.UserId;
                            this.plansService.SavePlanEvents(events);
                        }
                    }
                }

                this.ModelState.Clear();
                return this.RedirectToAction(nameof(this.PlanDetails), new { @planGuId = plans.PlanGUID });
            }
            catch (Exception ex)
            {
                this.logger.LogError(ex, ex.Message);
                return this.PartialView("Error", ex);
            }
        }
    }
}

src/SaaS.SDK.PublisherSolution/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Welcome";
}
<div class="pt-5 custom">
    <div class="page-title text-capitalize"><h1>Home</h1></div>

    <div class="card p-3 customcards">
        <div class="text-center">
            <h4 class="display-4" style="font-size:35px;">Welcome to the SaaS accelerator Admin page</h4>
        </div>
        <div class="text-left">
            <!--<p>This is the publisher solution.</p>-->
            @if (!this.User.Identity.IsAuthenticated)
            {
                <p> Please sign in to continue.</p>
            }

        </div>
    </div>
    <div class="pagequicklink text-capitalize"><h3>Quicklinks</h3></div>
    <ul id="homepage-programs">
        <li id="onedash-menu-homepage1">
            <a class="programCardLink text-capitalize" asp-area="" asp-controller="Home" asp-action="Subscriptions">Subscriptions</a>
            <div class="programCard">
                <div class="programCardContentWrapper">
                    <div class="programCardTitle minline">
                        <div class="programCardIcon1 wrap-win-icon-RecruitmentManagement">
                            <div class="win-icon win-icon-RecruitmentManagement">

                                <svg xmlns="http://www.w3.org/2000/svg" x="0px" y="0px"
                                     width="25" height="25"
                                     viewBox="0 0 172 172"
                                     style=" fill:#000000;">
                                    <g fill="none" fill-rule="nonzero" stroke="none" stroke-width="1" stroke-linecap="butt" stroke-linejoin="miter" stroke-miterlimit="10" stroke-dasharray="" stroke-dashoffset="0" font-family="none" font-weight="none" font-size="none" text-anchor="none" style="mix-blend-mode: normal"><path d="M0,172v-172h172v172z" fill="none"></path><g fill="#ffffff"><path d="M24.08,6.88v158.24h123.84v-114.9175l-0.9675,-1.075l-41.28,-41.28l-1.075,-0.9675zM30.96,13.76h68.8v41.28h41.28v103.2h-110.08zM106.64,18.705l29.455,29.455h-29.455z"></path></g></g>
                                </svg>

                            </div>
                        </div>
                        <div class="programCardTitleLeft">
                            <h5>Subscriptions</h5>
                        </div>

                        <div class="clear"></div>
                    </div>
                    <div class="clear"></div>
                    <div class="programCardContent">
                    </div>
                    <div class="programCardHelp pull-right">
                    </div>
                </div>
            </div>
        </li>
        <li id="onedash-menu-homepage2">
            <a class="programCardLink text-capitalize" asp-area="" asp-controller="Plans" asp-action="Index">Plans</a>
            <div class="programCard">
                <div class="programCardContentWrapper">
                    <div class="programCardTitle minline">
                        <div class="programCardIcon2 wrap-win-icon-RecruitmentManagement">
                            <div class="win-icon win-icon-RecruitmentManagement">
                                <svg xmlns="http://www.w3.org/2000/svg" x="0px" y="0px"
                                     width="25" height="25"
                                     viewBox="0 0 172 172"
                                     style=" fill:#000000;">
                                    <g fill="none" fill-rule="nonzero" stroke="none" stroke-width="1" stroke-linecap="butt" stroke-linejoin="miter" stroke-miterlimit="10" stroke-dasharray="" stroke-dashoffset="0" font-family="none" font-weight="none" font-size="none" text-anchor="none" style="mix-blend-mode: normal"><path d="M0,172v-172h172v172z" fill="none"></path><g fill="#ffffff"><path d="M21.5,32.25c-5.93706,0 -10.75,4.81294 -10.75,10.75c0,5.93706 4.81294,10.75 10.75,10.75c5.93706,0 10.75,-4.81294 10.75,-10.75c0,-5.93706 -4.81294,-10.75 -10.75,-10.75zM57.33333,35.83333c-2.58456,-0.03655 -4.98858,1.32136 -6.29153,3.55376c-1.30295,2.2324 -1.30295,4.99342 0,7.22582c1.30295,2.2324 3.70697,3.59031 6.29153,3.55376h93.16667c2.58456,0.03655 4.98858,-1.32136 6.29153,-3.55376c1.30295,-2.2324 1.30295,-4.99342 0,-7.22582c-1.30295,-2.2324 -3.70697,-3.59031 -6.29153,-3.55376zM21.5,75.25c-5.93706,0 -10.75,4.81294 -10.75,10.75c0,5.93706 4.81294,10.75 10.75,10.75c5.93706,0 10.75,-4.81294 10.75,-10.75c0,-5.93706 -4.81294,-10.75 -10.75,-10.75zM57.33333,78.83333c-2.58456,-0.03655 -4.98858,1.32136 -6.29153,3.55376c-1.30295,2.2324 -1.30295,4.99342 0,7.22582c1.30295,2.2324 3.70697,3.59031 6.29153,3.55376h93.16667c2.58456,0.03655 4.98858,-1.32136 6.29153,-3.55376c1.30295,-2.2324 1.30295,-4.99342 0,-7.22582c-1.30295,-2.2324 -3.70697,-3.59031 -6.29153,-3.55376zM21.5,118.25c-5.93706,0 -10.75,4.81294 -10.75,10.75c0,5.93706 4.81294,10.75 10.75,10.75c5.93706,0 10.75,-4.81294 10.75,-10.75c0,-5.93706 -4.81294,-10.75 -10.75,-10.75zM57.33333,121.83333c-2.58456,-0.03655 -4.98858,1.32136 -6.29153,3.55376c-1.30295,2.2324 -1.30295,4.99342 0,7.22582c1.30295,2.2324 3.70697,3.59031 6.29153,3.55376h93.16667c2.58456,0.03655 4.98858,-1.32136 6.29153,-3.55376c1.30295,-2.2324 1.30295,-4.99342 0,-7.22582c-1.30295,-2.2324 -3.70697,-3.59031 -6.29153,-3.55376z"></path></g></g>
                                </svg>
                            </div>
                        </div>
                        <div class="programCardTitleLeft">
                            <h5>Plans</h5>
                        </div>

                        <div class="clear"></div>
                    </div>
                    <div class="clear"></div>
                    <div class="programCardContent">
                    </div>
                    <div class="programCardHelp pull-right">
                    </div>
                </div>
            </div>
        </li>
        <li id="onedash-menu-homepage3">
            <a class="programCardLink text-capitalize" asp-area="" asp-controller="Offers" asp-action="Index">Offers</a>
            <div class="programCard">
                <div class="programCardContentWrapper">
                    <div class="programCardTitle minline">
                        <div class="programCardIcon3 wrap-win-icon-RecruitmentManagement">


                            <svg xmlns="http://www.w3.org/2000/svg" x="0px" y="0px"
                                 width="25" height="25"
                                 viewBox="0 0 172 172"
                                 style=" fill:#000000;">
                                <g fill="none" fill-rule="nonzero" stroke="none" stroke-width="1" stroke-linecap="butt" stroke-linejoin="miter" stroke-miterlimit="10" stroke-dasharray="" stroke-dashoffset="0" font-family="none" font-weight="none" font-size="none" text-anchor="none" style="mix-blend-mode: normal"><path d="M0,172v-172h172v172z" fill="none"></path><g fill="#ffffff"><path d="M17.2,13.76c-5.66077,0 -10.32,4.66306 -10.32,10.32v30.96v34.4v58.48c0,5.65694 4.65923,10.32 10.32,10.32h137.6c5.65902,0 10.32,-4.66098 10.32,-10.32v-58.48v-34.4v-17.2c0,-5.65902 -4.66098,-10.32 -10.32,-10.32h-92.88c0.2978,0 -0.10667,0.00125 -0.94735,-0.9675c-0.84067,-0.96875 -1.87545,-2.5759 -2.95625,-4.3c-1.08079,-1.7241 -2.21349,-3.5637 -3.64156,-5.18016c-1.42807,-1.61645 -3.39833,-3.31234 -6.21485,-3.31234zM17.2,20.64h30.96c-0.20898,0 0.21032,0.02411 1.06156,0.98766c0.85125,0.96355 1.88731,2.56394 2.96297,4.27984c1.07566,1.7159 2.18958,3.54875 3.58781,5.16c1.39823,1.61125 3.32316,3.3325 6.14765,3.3325h92.88c1.9365,0 3.44,1.5035 3.44,3.44v7.525c-1.08323,-0.39065 -2.22966,-0.645 -3.44,-0.645h-137.6c-1.21034,0 -2.35677,0.25435 -3.44,0.645v-21.285c0,-1.93858 1.49837,-3.44 3.44,-3.44zM17.2,51.6h137.6c1.9437,0 3.44,1.4963 3.44,3.44v34.4v58.48c0,1.9365 -1.5035,3.44 -3.44,3.44h-137.6c-1.94163,0 -3.44,-1.50142 -3.44,-3.44v-58.48v-34.4c0,-1.9437 1.4963,-3.44 3.44,-3.44z"></path></g></g>
                            </svg>

                        </div>
                        <div class="programCardTitleLeft">
                            <h5>Offers</h5>
                        </div>

                        <div class="clear"></div>
                    </div>
                    <div class="clear"></div>
                    <div class="programCardContent">
                    </div>
                    <div class="programCardHelp pull-right">
                    </div>
                </div>
            </div>
        </li>
    </ul>

</div>

src/SaaS.SDK.PublisherSolution/Views/Home/ProcessMessage.cshtml
@using Microsoft.Marketplace.SaaS.SDK.Services.Models
@using Microsoft.AspNetCore.Mvc.TagHelpers
@*@model Microsoft.Marketplace.SaasKit.Client.Models.SubscriptionResultExtensionSubscriptionResultExtension
    @{
        //ViewData["Title"] = "Home";
    }*@
<div class="container">
    <form method="post">
        <div class="cm-panel-default mt40">
            <div class="p-3">
                <p>
                    Processing your request.
                </p>
                <p>
                   Updated status of the activity is available in the subscription list.
                </p>
            </div>
        </div>
        <div class="text-right">
            <button type="submit" asp-action="Subscriptions" class="cm-button-default mt40 text-right">Go to Subscription List</button>
        </div>
    </form>
</div>

src/SaaS.SDK.PublisherSolution/Views/Home/RecordUsage.cshtml
@using Microsoft.Marketplace.SaaS.SDK.Services.Models
@model SubscriptionUsageViewModel
@{
    ViewData["Title"] = "RecordUsage";
}

@if (Model.SubscriptionDetail != null && Model.SubscriptionDetail.Id > 0)
{
    <div>
        <div class="container">
            <div class="card-body ">
                <br />
                <div class="form-group row">
                    <div class="col-md-12">
                        <div class="text-left">
                            <span class="cm-section-heading">Manage Subscription Usage</span>
                        </div>
                        <form asp-action="ManageSubscriptionUsage" method="post">
                            <div class="row p10">
                                <div class="col-md-1 pt-1">
                                    @Html.HiddenFor(s => s.SubscriptionDetail.Id)
                                    @Html.HiddenFor(s => s.SubscriptionDetail.AmpsubscriptionId)
                                    @Html.HiddenFor(s => s.SubscriptionDetail.AmpplanId)
                                    @Html.LabelFor(s => s.Quantity, new { @class = "font-weight-bold" })
                                </div>
                                <div class="col-md-2">
                                    @Html.TextBoxFor(s => s.Quantity, null, new { @class = "form-control", @placeholder = "Quantity", required = "required" })
                                </div>
                                <div class="col-md-1 pt-1">
                                    @Html.LabelFor(s => s.DimensionsList, "Dimension", new { @class = "font-weight-bold" })
                                </div>
                                <div class="col-md-3">
                                    @Html.DropDownListFor(s => s.SelectedDimension, Model.DimensionsList, "-- Select Dimension --", new { @class = "form-control", required = "required" })
                                </div>
                                <div class="col-md-2">
                                    <button type="submit" class="cm-button-default mt0">Record Usage</button>
                                </div>
                            </div>



                        </form>
                    </div>
                </div>
                <div class="form-group" style="overflow:auto" height="250px">
                    @if (Model.MeteredAuditLogs.Count() > 0)
                    {
                        <table id="table" class="table table-striped table-bordered dt-responsive" width="100%" cellspacing="0">
                            <thead>
                                <tr>
                                    <th>Subscription Usage Date(UTC)</th>
                                    <th>Status Code</th>
                                    <th>Request JSON</th>
                                    <th>Response JSON</th>
                                </tr>
                            </thead>
                            <tbody>
                                @for (var i = 0; i < Model.MeteredAuditLogs.Count; i++)
                                {
                                    var meteredAuditLog = Model.MeteredAuditLogs[i];
                                    <tr>
                                        <td class="text-left">
                                            @Html.HiddenFor(s => s.MeteredAuditLogs[i].Id)
                                            @Html.HiddenFor(s => s.MeteredAuditLogs[i].Subscription.Id)
                                            @meteredAuditLog.SubscriptionUsageDate
                                        </td>
                                        <td class="text-left">@meteredAuditLog.StatusCode</td>
                                        <td class="text-left">@meteredAuditLog.RequestJson</td>
                                        <td class="text-left">@meteredAuditLog.ResponseJson</td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    }
                    else
                    {
                        <div class="cm-panel-default mt40">
                            <div class="p-3 mr420">
                                <p>
                                    No licenses assigned yet, start assigning by selecting a subscription and submitting license key.
                                </p>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>

    </div>
}