src/SaaS.SDK.PublisherSolution/Controllers/ApplicationConfigController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.Logging;
using Microsoft.Marketplace.Saas.Web.Controllers;
using Microsoft.Marketplace.SaaS.SDK.Services.Services;
using Microsoft.Marketplace.SaaS.SDK.Services.Utilities;
using Microsoft.Marketplace.SaasKit.Client.DataAccess.Contracts;
using Microsoft.Marketplace.SaasKit.Client.DataAccess.Entities;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text.Json;

namespace SaaS.SDK.PublisherSolution.Controllers
{
    /// <summary>
    /// Offers Controller.
    /// </summary>
    /// <seealso cref="Microsoft.Marketplace.Saas.Web.Controllers.BaseController" />
    [ServiceFilter(typeof(KnownUserAttribute))]
    public class ApplicationConfigController : BaseController
    {
        private readonly ILogger<ApplicationConfigController> logger;

        private ApplicationConfigService appConfigService;

        private readonly IApplicationConfigRepository appConfigRepository;

        public ApplicationConfigController(IApplicationConfigRepository applicationConfigRepository, ILogger<ApplicationConfigController> logger)
        {
            this.appConfigRepository = applicationConfigRepository;
            this.logger = logger;
            appConfigService = new ApplicationConfigService(this.appConfigRepository);
        }

        /// <summary>
        /// Indexes this instance.
        /// </summary>
        /// <returns>return All Application Config.</returns>
        public IActionResult Index()
        {
            this.logger.LogInformation("Application Config Controller / Index");
            try
            {
                IEnumerable<ApplicationConfiguration> getAllAppConfigData = new List<ApplicationConfiguration>();
                getAllAppConfigData = this.appConfigService.GetAllApplicationConfiguration();
                return this.View(getAllAppConfigData);
            }
            catch (Exception ex)
            {
                this.logger.LogError(ex, ex.Message);
                return this.View("Error", ex);
            }
        }

        /// <summary>
        /// Get the apllication config item by Id.
        /// </summary>
        /// <param name="Id">The app config Id.</param>
        /// <returns>
        /// return an Application Config item.
        /// </returns>
        public IActionResult ApplicationConfigDetails(int Id)
        {
            this.logger.LogInformation("ApplicationConfig Controller / AppConfigDetails:  Id {0}", Id);
            try
            {
                ApplicationConfiguration applicationConfiguration = new ApplicationConfiguration();
                applicationConfiguration = this.appConfigService.GetById(Id);
                return this.PartialView(applicationConfiguration);
            }
            catch (Exception ex)
            {
                this.logger.LogError(ex, ex.Message);
                return this.View("Error", ex);
            }
        }

        /// <summary>
        /// Saves the app config item changes.
        /// </summary>
        /// <param name="appConfig">The app config item.</param>
        /// <returns>
        /// return the changed app config item.
        /// </returns>
        [HttpPost]
        public IActionResult ApplicationConfigDetails(ApplicationConfiguration appConfig)
        {
            this.logger.LogInformation("ApplicationConfig Controller / ApplicationConfigDetails:  AppConfig {0}", JsonSerializer.Serialize(appConfig));
            try
            {
                if (appConfig != null)
                {
                    this.appConfigService.SaveAppConfig(appConfig);
                }

                this.ModelState.Clear();
                return this.RedirectToAction(nameof(this.ApplicationConfigDetails), new { Id = appConfig.Id });
            }
            catch (Exception ex)
            {
                this.logger.LogError(ex, ex.Message);
                return this.PartialView("Error", ex);
            }
        }

        /// <summary>
        /// Upload file(s) to database
        /// </summary>
        /// <param name="files">The files</param>
        /// <returns>RedirectToAction.</returns>
        [HttpPost("FileUpload")]
        public IActionResult PostUpload(List<IFormFile> files)
        {
            this.logger.LogInformation("Application Config Controller / PostUpload ");
            try
            {
                if (files == null || files.Count == 0)
                {
                    TempData["Upload"] = "No files to upload";
                    return RedirectToAction("Index");
                }
                else
                {
                    if (files.Count > 2)
                    {
                        TempData["Upload"] = "No more than two files can be uploaded";
                        return RedirectToAction("Index");
                    }       
                    foreach (var file in files)
                    {
                        int maxLength = 1024 * 1024 * 5; //5 MB

                        if (file.Length > maxLength)
                        {
                            TempData["Upload"] = "File is too large, max size of file for upload is 5 MB";
                            return RedirectToAction("Index");
                        }
                        if (file.Length == 0)
                        {
                            TempData["Upload"] = "File is empty";
                            return RedirectToAction("Index");
                        }

                        var fileExtension = Path.GetExtension(file.FileName).ToLowerInvariant();

                        if (fileExtension != ".png" && fileExtension != ".ico")
                        {
                            TempData["Upload"] = "Only .png or .ico files can be uploaded";
                            return RedirectToAction("Index");
                        }

                        var appConfigNames = this.appConfigService.GetAllApplicationConfiguration().Select(a => a.Name);
                       
                        if (!appConfigNames.Contains("LogoFile") || !appConfigNames.Contains("FaviconFile"))
                        {
                            TempData["Upload"] = "LogoFile or FaviconFile application config settings are missing in the database";
                            return RedirectToAction("Index");
                        }

                        if (this.appConfigService.UploadFileToDatabase(file, fileExtension) == false)
                        {
                            TempData["Upload"] = "File Upload failed!";
                            return RedirectToAction("Index");
                        }
                    }

                    if (files.Count == 1)
                    {
                        TempData["Upload"] = files.FirstOrDefault().FileName + "  uploaded successfully";
                    }
                    else
                    {
                        TempData["Upload"] = files[0].FileName + " and " + files[1].FileName + " uploaded successfully";
                    }
                }
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                this.logger.LogError(ex, ex.Message);
                TempData["Upload"] = "File Upload failed!";
                return this.PartialView("Error", ex);
            }
        }

    }
}

src/SaaS.SDK.PublisherSolution/Views/ApplicationConfig/ApplicationConfigDetails.cshtml
@using Microsoft.Marketplace.SaaS.SDK.Services.Models
@using Microsoft.Marketplace.SaasKit.Client.DataAccess.Entities;
@model ApplicationConfiguration
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="~/css/jquery-ui/jquery-ui.css" rel="stylesheet" />
    <link href="~/css/jquery-ui/style.css" rel="stylesheet" />
    <script src="~/lib/jquery-ui/jquery-1.12.4.js"></script>
    <script src="~/lib/jquery-ui/jquery-ui.js"></script>
</head>
<body>

    <div class="text-center mt20">
        <div class="card card-header">
            <dl class="row">
                <dt class="col-2 text-right"><span>Edit App Config</span></dt>
            </dl>
        </div>
        <form method="post" id="frmAppConfigDetails" asp-action="ApplicationConfigDetails" asp-controller="ApplicationConfig">
            <div>
                @Html.HiddenFor(model => model.Id)
            </div>
            <table class="table table-bordered dt-responsive cm-table" id="tblcontainer">
                <theader>
                    <tr>
                        <th>Name</th>
                        <th>Value</th>
                        <th>Description</th>
                    </tr>
                </theader>
                <tbody>
                <tr>
                    <td>
                        @Model.Name
                    </td>
                    <td>
                        @if (@Model.Name.Equals("SMTPPassword") && @Model.Value.Length >5)
                        {
                            @Html.EditorFor(model => model.Value, new { htmlAttributes = new { type ="password", @class = "form-control" } })
                        }
                        else
                        {
                            @Html.EditorFor(model => model.Value, new { htmlAttributes = new { @class = "form-control" } })
                        }
                    </td>
                    <td>
                        @Html.EditorFor(model => model.Description,new { htmlAttributes = new { @class = "form-control" } })
                    </td>
                </tr>
                </tbody>
            </table>
            <div class="ac-save-d">
                <p>
                    <a class="cm-button-default mt0" id="backButton" asp-area="" asp-controller="ApplicationConfig" asp-action="Index">Back</a>
                    <input class="cm-button-default mt0 ac-save-i" type="button" onclick="saveAppConfigDetails()" value="Save App Config" />
                </p>
            </div>
        </form>
    </div>


</body>
<script>

    function successconfirmDialog() {
        swal({
            title: "Saved",
            text: "App config details saved successfully.",
            icon: "success",
            timer: 1000
        })
    }
    function errorconfirmDialog() {
        swal({
            title: "Error",
            text: "An error has occured, please check the log.",
            icon: "error",
            timer: 1000
        })
    }
    function saveAppConfigDetails() {
        var formobject = $('#frmAppConfigDetails').serialize();
        $.ajax({
            url: 'ApplicationConfig/ApplicationConfigDetails',
            type: 'POST',
            data: formobject,
            cache: false,
            success: function (result) {
                debugger;
                successconfirmDialog();
                $('#myModal').html(result);
            },
            Error:
                function (result) {
                    errorconfirmDialog();
                    $('#myModal').html(result);
                }
        });
    }

</script>

src/SaaS.SDK.PublisherSolution/Views/ApplicationConfig/Index.cshtml
@using Microsoft.Marketplace.SaaS.SDK.Services.Models
@using Microsoft.Marketplace.SaasKit.Client.DataAccess.Entities
@model IEnumerable<ApplicationConfiguration>
@{
    ViewData["Title"] = "Index";
}

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" />
<div class="container">
    <div class="">
        <div class="card-body admin-margin">
            <div class="text-left">
                <span class="cm-section-heading">Application Config</span>
            </div>
            <div id="myModal">
                <div class="table-responsive mt20">
                    <table class="table table-bordered dt-responsive cm-table" width="100%" cellspacing="0" id="applicationConfig">
                        <thead class="cm-table-head">
                            <tr>
                                <th>Config Name</th>
                                <th>Config Value</th>
                                <th>Config Description</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @{ var i = 0;}
                            @foreach (var item in Model)
                            {
                                @if (@item.Name.Equals("LogoFile") || @item.Name.Equals("FaviconFile")) continue;
                                <tr>
                                    <td class="text-left">
                                        @item.Name
                                    </td>
                                    <td class="text-left">
                                        @if (@item.Name.Equals("SMTPPassword") && @item.Value.Length > 5)
                                        {
                                            @String.Format("{0}{1}", @item.Value.Substring(0,5), "****************");
                                        }
                                        else
                                        {
                                            @item.Value
                                        }
                                    </td>
                                    <td class="text-left">
                                        @item.Description
                                    </td>
                                    <td class="text-left cm-ellipsis">
                                        <div class="nav-item dropdown">
                                            <a class="nav-link dropdown cm-link-button" href="#" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fa fa-bars"></i></a>
                                            <div class="dropdown-menu" aria-labelledby="dropdown01">
                                                <a class="dropdown-item cm-dropdown-option" data-target="#myModal" onclick="ViewAppConfigdetailsById('@item.Id')">Edit</a>
                                            </div>
                                        </div>
                                    </td>
                                </tr>
                                i++;
                            }
                        </tbody>
                    </table>
                </div>
                <hr />
                <h2>Upload Logo</h2>
                <p style="font-size:10px;">*restart the application after uploading file(s) and refresh (ctrl F5) to see the new logo/favicon</p>
                <div class="row">
                    <section>
                        <form method="post" enctype="multipart/form-data"
                              asp-controller="FileUpload" asp-action="Index">
                            <div class="form-group">
                                <div class="col-md-10">
                                    <input type="file" name="files" accept=".ico, .png" multiple />
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-md-10">
                                    <input type="submit" class="btn btn-primary" onclick = "changeValue()" value="Upload" />
                                </div>
                            </div>
                        </form>
                    </section>
                </div>
                <label id="tempdataLabel">@TempData["Upload"]</label> 
            </div>
        </div>
    </div>
</div>
<script>
    function changeValue(){
        document.getElementById('tempdataLabel').innerHTML="In progress ..."    
    }

    function ViewAppConfigdetailsById(Id) {
            $.ajax({
                type: "Get",
                url: "ApplicationConfig/ApplicationConfigDetails",
                data: { Id: Id },
                contentType: "application/json; charset=utf-8",
                datatype: "json",
                success: function (data) {
                    $('#myModal').html(data);
                    //$('#myModal').modal();
                },
                error: function () {
                    alert("Content load failed.");
                }
            });
        }

</script>